---
name: macos

on:
  - push

jobs:
  perl:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40"
      - run: perl -V
      - run: cpanm --installdeps .
      - run: cpanm -n TAP::Formatter::GitHubActions
      - name: Run Tests
        run: prove --merge --formatter TAP::Formatter::GitHubActions -l t
