---
name: macos

on:
  - push

jobs:
  perl:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40"
      - run: perl -V
      - run: cpanm -nq Dist::Zilla
      - name: Install author and runtime dependencies
        run: |
          dzil authordeps --missing | cpanm -nq
          dzil listdeps --develop --missing | cpanm -nq
      - name: Run tests
        run: dzil test --all
