---
name: windows

on:
  - push

jobs:
  perl:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40"
          distribution: strawberry
      - run: perl -V
      - run: cpanm -nq Dist::Zilla
      - name: Install author and runtime dependencies
        run: |
          dzil authordeps --missing | cpanm -nq
          dzil listdeps --develop --missing | cpanm -nq
      - name: Run tests
        run: dzil test --all
